@echo off
chcp 65001 >nul
echo ========================================
echo 配置 Android SDK 路径
echo ========================================
echo.

:: 检查当前目录
if exist "ar_hand_tracking\build.gradle" (
    set TARGET_DIR=.
    echo ✓ 检测到 solutions 目录
) else if exist "mediapipe\examples\android\solutions\ar_hand_tracking\build.gradle" (
    set TARGET_DIR=mediapipe\examples\android\solutions
    echo ✓ 检测到 mediapipe 根目录
) else (
    echo [错误] 找不到项目目录
    pause
    exit /b 1
)

echo.
echo 正在查找 Android SDK...
echo.

:: 尝试常见的 SDK 位置
set SDK_PATH=

:: 检查 ANDROID_HOME 环境变量
if defined ANDROID_HOME (
    if exist "%ANDROID_HOME%\platform-tools\adb.exe" (
        set SDK_PATH=%ANDROID_HOME%
        echo ✓ 从 ANDROID_HOME 找到 SDK: %SDK_PATH%
        goto :found_sdk
    )
)

:: 检查 ANDROID_SDK_ROOT 环境变量
if defined ANDROID_SDK_ROOT (
    if exist "%ANDROID_SDK_ROOT%\platform-tools\adb.exe" (
        set SDK_PATH=%ANDROID_SDK_ROOT%
        echo ✓ 从 ANDROID_SDK_ROOT 找到 SDK: %SDK_PATH%
        goto :found_sdk
    )
)

:: 检查默认位置
if exist "%LOCALAPPDATA%\Android\Sdk\platform-tools\adb.exe" (
    set SDK_PATH=%LOCALAPPDATA%\Android\Sdk
    echo ✓ 在默认位置找到 SDK: %SDK_PATH%
    goto :found_sdk
)

if exist "%USERPROFILE%\AppData\Local\Android\Sdk\platform-tools\adb.exe" (
    set SDK_PATH=%USERPROFILE%\AppData\Local\Android\Sdk
    echo ✓ 在用户目录找到 SDK: %SDK_PATH%
    goto :found_sdk
)

:: 未找到 SDK
echo [错误] 未找到 Android SDK
echo.
echo 请手动输入 Android SDK 路径，例如：
echo C:\Users\YourName\AppData\Local\Android\Sdk
echo.
echo 或者打开 Android Studio，SDK 路径在：
echo   File → Settings → Appearance ^& Behavior → System Settings → Android SDK
echo.
set /p SDK_PATH="请输入 SDK 路径（或按 Ctrl+C 取消）: "

if not exist "%SDK_PATH%\platform-tools\adb.exe" (
    echo.
    echo [错误] 路径无效，找不到 adb.exe
    pause
    exit /b 1
)

:found_sdk
echo.
echo ========================================
echo SDK 路径: %SDK_PATH%
echo ========================================
echo.

:: 将路径转换为正确的格式（Unix 风格的斜杠）
set SDK_PATH_FORMATTED=%SDK_PATH:\=/%

:: 创建 local.properties 文件
echo 创建 local.properties 文件...
(
echo # Auto-generated by setup_sdk.bat
echo # Location of the Android SDK
echo sdk.dir=%SDK_PATH_FORMATTED%
) > "%TARGET_DIR%\local.properties"

if exist "%TARGET_DIR%\local.properties" (
    echo ✓ local.properties 创建成功
    echo.
    echo 文件内容：
    type "%TARGET_DIR%\local.properties"
    echo.
    echo ========================================
    echo ✓ 配置完成！
    echo ========================================
    echo.
    echo 现在可以运行编译命令了：
    echo   cd %TARGET_DIR%
    echo   gradlew.bat :ar_hand_tracking:assembleDebug
) else (
    echo [错误] 创建 local.properties 失败
    pause
    exit /b 1
)

echo.
pause
